//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAssessment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevAssessment.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Assessment.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Device Orientation.
        /// </summary>
        internal static string ButtonGetDeviceOrientation {
            get {
                return ResourceManager.GetString("ButtonGetDeviceOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo.
        /// </summary>
        internal static string ButtonPickPhoto {
            get {
                return ResourceManager.GetString("ButtonPickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say Hello World.
        /// </summary>
        internal static string ButtonSayHelloWorld {
            get {
                return ResourceManager.GetString("ButtonSayHelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Orientation.
        /// </summary>
        internal static string DeviceOrientationPageTitle {
            get {
                return ResourceManager.GetString("DeviceOrientationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Orientation.
        /// </summary>
        internal static string LabelDeviceOrientation {
            get {
                return ResourceManager.GetString("LabelDeviceOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string LabelLandscape {
            get {
                return ResourceManager.GetString("LabelLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LabelLogout {
            get {
                return ResourceManager.GetString("LabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Picker.
        /// </summary>
        internal static string LabelPhotoPicker {
            get {
                return ResourceManager.GetString("LabelPhotoPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string LabelPortait {
            get {
                return ResourceManager.GetString("LabelPortait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        internal static string LabelRole {
            get {
                return ResourceManager.GetString("LabelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Speech.
        /// </summary>
        internal static string LabelTextToSpeech {
            get {
                return ResourceManager.GetString("LabelTextToSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string LabelUndefined {
            get {
                return ResourceManager.GetString("LabelUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Picker.
        /// </summary>
        internal static string PhotoPickerPageTitle {
            get {
                return ResourceManager.GetString("PhotoPickerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text To Speech.
        /// </summary>
        internal static string TextToSpeechPagetTitle {
            get {
                return ResourceManager.GetString("TextToSpeechPagetTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alert Display.
        /// </summary>
        internal static string AlertDisplayTitle
        {
            get
            {
                return ResourceManager.GetString("AlertDisplayTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error Display.
        /// </summary>
        internal static string ErrorDisplayTitle
        {
            get
            {
                return ResourceManager.GetString("ErrorDisplayTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsReaderPageTitle
        {
            get
            {
                return ResourceManager.GetString("NewsReaderPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to News Source List.
        /// </summary>
        internal static string LabelNewsSourceList
        {
            get
            {
                return ResourceManager.GetString("LabelNewsSourceList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source List.
        /// </summary>
        internal static string LabelSourceList
        {
            get
            {
                return ResourceManager.GetString("LabelSourceList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to News Category.
        /// </summary>
        internal static string NewsCategoryPageTitle
        {
            get
            {
                return ResourceManager.GetString("NewsCategoryPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string LoadingText
        {
            get
            {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK
        {
            get
            {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to News Reader Source.
        /// </summary>
        internal static string NewsReaderSourcePageTitle
        {
            get
            {
                return ResourceManager.GetString("NewsReaderSourcePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to News Reader Source.
        /// </summary>
        internal static string LabelDisableAllSources
        {
            get
            {
                return ResourceManager.GetString("LabelDisableAllSources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string ArticlePageTitle
        {
            get
            {
                return ResourceManager.GetString("ArticlePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string LabelCategories
        {
            get
            {
                return ResourceManager.GetString("LabelCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internet Not Available.
        /// </summary>
        internal static string LabelInternetNotAvailable
        {
            get
            {
                return ResourceManager.GetString("LabelInternetNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string BusinessText
        {
            get
            {
                return ResourceManager.GetString("BusinessText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string EntertainmentText
        {
            get
            {
                return ResourceManager.GetString("EntertainmentText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralText
        {
            get
            {
                return ResourceManager.GetString("GeneralText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string HealthText
        {
            get
            {
                return ResourceManager.GetString("HealthText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Science.
        /// </summary>
        internal static string ScienceText
        {
            get
            {
                return ResourceManager.GetString("ScienceText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string SportsText
        {
            get
            {
                return ResourceManager.GetString("SportsText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        internal static string TechnologyText
        {
            get
            {
                return ResourceManager.GetString("TechnologyText", resourceCulture);
            }
        }
    }
}
